spring:
  profiles:
    include:
      - oauth
      - redis
      - jwt

  datasource:
    url: jdbc:h2:mem:test
    name: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console